workspace:
  base: /drone
  path: src/github.com/qnib/go-testhttpd

pipeline:
  unit-test:
    image: qnib/golang
    commands:
     - ./test.sh
    environment:
     - GOPATH=/drone/
  smoke-test:
    image: qnib/golang
    commands:
     - go run main.go --help
    environment:
     - GOPATH=/drone/
  build:
    image: qnib/alpn-go-dev:1.7
    commands:
      - mkdir -p resources/bin
      - go build -o resources/bin/go-testhttpd_musl
      - GOOS=darwin GOARCH=amd64 go build -o resources/bin/go-testhttpd_darwin
    environment:
     - GOPATH=/drone/
    when:
        event: tag
  build:
    image: qnib/golang
    commands:
      - go build -o resources/bin/go-testhttpd_linux
    environment:
     - GOPATH=/drone/
    when:
        event: tag
  slack:
    image: plugins/slack
    channel: drone
    username: drone
